import { describe, it, expect } from 'vitest';
import { ConnectionGraph } from '../graph.js';
import { renderMarkdown } from './markdown-renderer.js';
import { JsTsAnalyzer } from '../analyzer/js-ts-analyzer.js';
import { registerDataArtifacts } from '../data/formats.js';

describe('renderMarkdown', () => {
  it('renders repository overview and metadata', () => {
    const graph = new ConnectionGraph();
    graph.addFile('src/main.ts', 'typescript');
    const map = graph.build({ commit: 'a81f32c', generatedAt: '2026-10-01T21:20:00.000Z' });

    const md = renderMarkdown(map);

    expect(md).toContain('# Repository Connection Map');
    expect(md).toContain('Generated: 2026-10-01T21:20:00.000Z');
    expect(md).toContain('Commit: a81f32c');
    expect(md).toContain('## Repository Overview');
    expect(md).toContain('- **Files**: 1');
    expect(md).toContain('- **Symbols**: 0');
    expect(md).toContain('- **Data Artifacts**: 0');
    expect(md).toContain('## Machine-Readable Graph');
  });

  it('renders file connections with imports and importedBy', () => {
    const graph = new ConnectionGraph();
    graph.addFile('src/main.ts', 'typescript');
    graph.addFile('src/util.ts', 'typescript');
    graph.addRelationship('imports', 'src/main.ts', 'src/util.ts');
    graph.addRelationship('importedBy', 'src/util.ts', 'src/main.ts');

    const map = graph.build({ generatedAt: '2026-10-01T00:00:00Z' });
    const md = renderMarkdown(map);

    expect(md).toContain('## File Connections');
    expect(md).toContain('### src/main.ts (typescript)');
    expect(md).toContain('  → src/util.ts');
    expect(md).toContain('### src/util.ts (typescript)');
    expect(md).toContain('  ← src/main.ts');
  });

  it('renders symbol connections with calls, calledBy, extends, implements', () => {
    const graph = new ConnectionGraph();
    graph.addFile('src/app.ts', 'typescript');
    graph.addSymbol('src/app.ts', 'AppService', 'class');
    graph.addSymbol('src/base.ts', 'BaseService', 'class');

    graph.addRelationship('extends', 'src/app.ts:AppService', 'src/base.ts:BaseService');
    graph.addRelationship('calls', 'src/app.ts:AppService.run', 'src/util.ts:format');
    graph.addRelationship('calledBy', 'src/util.ts:format', 'src/app.ts:AppService.run');

    const map = graph.build({ generatedAt: '2026-10-01T00:00:00Z' });
    const md = renderMarkdown(map);

    expect(md).toContain('## Symbol Connections');
    expect(md).toContain('### src/app.ts:AppService [class]');
    expect(md).toContain('Extends:');
    expect(md).toContain('  → src/base.ts:BaseService');
    expect(md).toContain('Calls:');
    expect(md).toContain('  → src/util.ts:format');
  });

  it('renders data connections with generatedBy and consumedBy', () => {
    const graph = new ConnectionGraph();
    graph.addArtifact('data/titles.parquet', 'parquet');
    graph.addRelationship('generates', 'scripts/build.py', 'data/titles.parquet');
    graph.addRelationship('generatedBy', 'data/titles.parquet', 'scripts/build.py');
    graph.addRelationship('consumes', 'src/data/loadTitles.ts', 'data/titles.parquet');
    graph.addRelationship('consumedBy', 'data/titles.parquet', 'src/data/loadTitles.ts');

    const map = graph.build({ generatedAt: '2026-10-01T00:00:00Z' });
    const md = renderMarkdown(map);

    expect(md).toContain('## Data Connections');
    expect(md).toContain('### data/titles.parquet (parquet)');
    expect(md).toContain('Generated by:');
    expect(md).toContain('  ← scripts/build.py');
    expect(md).toContain('Consumed by:');
    expect(md).toContain('  → src/data/loadTitles.ts');
  });

  it('produces 100% deterministic markdown output', () => {
    const graph1 = new ConnectionGraph();
    graph1.addFile('src/b.ts');
    graph1.addFile('src/a.ts');
    graph1.addRelationship('imports', 'src/b.ts', 'src/a.ts');

    const graph2 = new ConnectionGraph();
    graph2.addFile('src/a.ts');
    graph2.addFile('src/b.ts');
    graph2.addRelationship('imports', 'src/b.ts', 'src/a.ts');

    const meta = { generatedAt: '2026-10-01T00:00:00Z' };
    const md1 = renderMarkdown(graph1.build(meta));
    const md2 = renderMarkdown(graph2.build(meta));

    expect(md1).toBe(md2);
  });

  it('renders full multi-file data pipeline graph into complete markdown', () => {
    const graph = new ConnectionGraph();
    const analyzer = new JsTsAnalyzer();
    const knownFiles = [
      'scripts/collect.js',
      'scripts/build.js',
      'data/raw.json',
      'data/titles.parquet',
      'src/data/loadTitles.ts',
      'src/pages/TitlesPage.tsx',
    ];

    registerDataArtifacts(knownFiles, graph);

    analyzer.analyzeFile(
      'scripts/collect.js',
      'const fs = require("fs"); fs.writeFileSync("data/raw.json", "[]");',
      graph,
      { knownFiles },
    );

    analyzer.analyzeFile(
      'scripts/build.js',
      'const fs = require("fs"); const r = fs.readFileSync("data/raw.json"); fs.writeFileSync("data/titles.parquet", r);',
      graph,
      { knownFiles },
    );

    analyzer.analyzeFile(
      'src/data/loadTitles.ts',
      'import { read } from "./lib.js"; export function loadTitles() { return read("data/titles.parquet"); }',
      graph,
      { knownFiles },
    );

    analyzer.analyzeFile(
      'src/pages/TitlesPage.tsx',
      'import { loadTitles } from "../data/loadTitles.js"; export function TitlesPage() { return loadTitles(); }',
      graph,
      { knownFiles },
    );

    const map = graph.build({ commit: 'm4pipeline', generatedAt: '2026-10-01T00:00:00Z' });
    const md = renderMarkdown(map);

    // Verify all sections exist and contain correct markdown output
    expect(md).toContain('# Repository Connection Map');
    expect(md).toContain('## Repository Overview');
    expect(md).toContain('## File Connections');
    expect(md).toContain('## Symbol Connections');
    expect(md).toContain('## Data Connections');
    expect(md).toContain('## Machine-Readable Graph');
  });
});
