import type { ConnectionMap, Relationship } from '../types.js';

export interface FormattedPath {
  readonly target: string;
  readonly steps: readonly string[];
}

/**
 * Options for graph path finding.
 */
export interface PathFinderOptions {
  /** Maximum traversal depth for paths (default: 4) */
  readonly maxDepth?: number;
  /** Maximum number of paths to generate per target (default: 3) */
  readonly maxPathsPerTarget?: number;
  /** Maximum total number of path sections in markdown output (default: 10) */
  readonly maxTotalPaths?: number;
}

/**
 * Discover key connection paths through the connection graph.
 *
 * Prioritizes paths involving data artifacts and multi-stage file pipelines.
 */
export function findConnectionPaths(
  map: ConnectionMap,
  options?: PathFinderOptions,
): readonly FormattedPath[] {
  const maxDepth = options?.maxDepth ?? 4;
  const maxPaths = options?.maxPathsPerTarget ?? 3;
  const maxTotal = options?.maxTotalPaths ?? 10;

  // Build adjacency map: node -> relationships originating from node
  const outgoing = new Map<string, Relationship[]>();
  for (const rel of map.relationships) {
    if (!outgoing.has(rel.from)) outgoing.set(rel.from, []);
    outgoing.get(rel.from)?.push(rel);
  }

  const paths: FormattedPath[] = [];

  // Targets to trace: Data artifacts and entry point files
  const targets = Object.keys(map.artifacts).sort();

  for (const target of targets) {
    if (paths.length >= maxTotal) break;

    const targetPaths: string[][] = [];
    const visited = new Set<string>();

    function dfs(currentNode: string, currentPath: string[], depth: number): void {
      if (depth > maxDepth || targetPaths.length >= maxPaths) return;
      if (visited.has(currentNode)) return;

      visited.add(currentNode);
      currentPath.push(currentNode);

      const rels = outgoing.get(currentNode) ?? [];

      if (rels.length === 0 && currentPath.length > 2) {
        targetPaths.push([...currentPath]);
      } else {
        for (const rel of rels) {
          const stepDesc = formatStepRelation(rel);
          currentPath.push(stepDesc);
          dfs(rel.to, currentPath, depth + 1);
          currentPath.pop();
        }
      }

      currentPath.pop();
      visited.delete(currentNode);
    }

    // Find incoming relationships to this artifact to start trace from producers
    const producers = map.relationships.filter(
      (r) => (r.to === target && r.type === 'generates') || r.to === target,
    );

    if (producers.length > 0) {
      for (const prod of producers) {
        if (targetPaths.length >= maxPaths) break;
        const initialPath = [prod.from, formatStepRelation(prod)];
        dfs(target, initialPath, 1);
      }
    } else {
      dfs(target, [], 0);
    }

    if (targetPaths.length > 0) {
      for (const p of targetPaths.slice(0, maxPaths)) {
        if (paths.length >= maxTotal) break;
        paths.push({
          target,
          steps: p,
        });
      }
    }
  }

  return paths;
}

function formatStepRelation(rel: Relationship): string {
  switch (rel.type) {
    case 'generates':
      return '→ generates →';
    case 'generatedBy':
      return '← generated by ←';
    case 'consumes':
      return '→ consumes →';
    case 'consumedBy':
      return '← consumed by ←';
    case 'imports':
      return '→ imports →';
    case 'importedBy':
      return '← imported by ←';
    case 'calls':
      return '→ calls →';
    case 'calledBy':
      return '← called by ←';
    case 'extends':
      return '→ extends →';
    case 'implements':
      return '→ implements →';
    default:
      return `→ ${rel.type} →`;
  }
}
